[package]
name = "dTwenteez"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)']}

[dependencies]
rand = "0.9.0"
regex = "1.11.1"
